<script language="JavaScript">
<!--
var MenuPrincipal = [
	[null,'Inicio','/',null,'Inicio'],
	[null,'Inter. Comerciales',null,null,'Ventas clientes',
		[null,'Proveedores','proveedores',null,'Proveedores'],
		[null,'Clientes','clientes', null,'Clientes']
	],
	[null,'Productos',null,null,'Productos',
		[null,'Articulos','articulos',null,'Articulos'],
		[null,'Familias','familias',null,'Familias']
	],
	[null,'Ventas clientes',null,null,'Ventas clientes',
		[null,'Partes de Trabajo','partes_trabajo',null,'Partes de Trabajo'],
		[null,'Presupuestos','presupuestos_clientes',null,'Presupuestos'],
		[null,'Albaranes','albaranes_clientes',null,'Albaranes'],
		[null,'Facturar albaranes','./lote_albaranes_clientes/index.php','principal','Facturar albaranes'],
		[null,'Ventas Mostrador','./ventas_mostrador/index.php','principal','Ventas Mostrador'],
		[null,'Facturas','./facturas_clientes/index.php','principal','Facturas']
	],
	[null,'Compras proveedores',null,null,'Compras proveedores',
		[null,'Facturas','./facturas_proveedores/index.php','principal','Proveedores'],
		[null,'Albaranes','./albaranes_proveedores/index.php','principal','Albaranes'],
		[null,'Facturar albaranes','./lote_albaranes_proveedores/index.php','principal','Facturar albaranes'],
	],
	[null,'Tesoreria',null,null,'Tesoreria',
		[null,'Cobros','./cobros/index.php','principal','Cobros'],
		[null,'Pagos','./pagos/index.php','principal','Pagos'],
		[null,'Caja Diaria','./cerrarcaja/index.php','principal','Caja Diaria'],
		[null,'Libro Diario','./librodiario/index.php','principal','Libro Diario'],
	],
	[null,'Mantenimientos',null,null,'Mantenimientos',
		[null,'Trabajadores','./trabajadores/index.php','principal','Trabajadores'],
		[null,'Etiquetas','./etiquetas/index.php','principal','Etiquetas'],
		[null,'Impuestos','./impuestos/index.php','principal','Impuestos'],
		[null,'Entidades bancarias','./entidades/index.php','principal','Entidades bancarias'],
		[null,'Ubicaciones','./ubicaciones/index.php','principal','Ubicaciones'],
		[null,'Embalajes','./embalajes/index.php','principal','Embalajes'],
		[null,'Formas de pago','./formaspago/index.php','principal','Formas de pago'],
	],
	[null,'Copias Seguridad',null,null,'Copias de Seguridad',
		[null,'Hacer copia','./backup/hacerbak.php','principal','Hacer copia'],
		[null,'Restaurar copia','./backup/restaurarbak.php','principal','Restaurar copia'],
	],
	[null,'Creditos','creditos.php','principal','Creditos']
];

--></script>
  <style type="text/css">
  body { background-color: rgb(255, 255,255);
    background-image: url(images/superior.png);
    background-repeat: no-repeat;
	margin: 0px;
    }

  #MenuAplicacion { margin-left: 10px;
    margin-top: 0px;
    }


  </style>
  
 <div id="MenuAplicacion" align="center"></div>
<script language="JavaScript">
<!--
	cmDraw ('MenuAplicacion', MenuPrincipal, 'hbr', cmThemeGray, 'ThemeGray');
-->
</script>
