		<div id="pagina">
			<div id="zonaContenido">
				<div align="center">
				<div id="tituloForm" class="header">INSERTAR PROVEEDOR </div>
				<div id="frmBusqueda">
				<?php echo Form::open(); ?>
					<table class="fuente8" width="98%" cellspacing=0 cellpadding=3 border=0>
						<tr>
							<td width="15%">Nombre</td>
						    <td width="43%"><?php echo Form::text('proveedor.nombre') ?></td>
					        <td width="42%" rowspan="12" align="left" valign="top"><?php View::content(); ?></td>
						</tr>
						<tr>
						  <td>NIF / CIF</td>
						  <td><?php echo Form::text('proveedor.nif') ?></td>
				      </tr>
						<tr>
						  <td>Direcci&oacute;n</td>
						  <td><?php echo Form::text('proveedor.direccion') ?></td>
				      </tr>
						<tr>
						  <td>Localidad</td>
						  <td><?php echo Form::text('proveedor.localidad') ?></td>
				      </tr>
						<tr>
							<td width="15%">Provincia</td>
							<td width="43%"><?php echo Form::dbSelect('proveedor.provincias_id'); ?></td>
				        </tr>
						<tr>
							<td width="15%">Entidad Bancaria</td>
							<td width="43%"><?php echo Form::dbSelect('proveedor.entidades_id'); ?></td>
				        </tr>
						<tr>
							<td>Cuenta bancaria</td>
							<td><?php echo Form::text('proveedor.cuentabancaria'); ?></td>
					    </tr>
						<tr>
							<td>C&oacute;digo postal </td>
							<td><?php echo Form::text('proveedor.codpostal'); ?></td>
					    </tr>
						<tr>
							<td>Tel&eacute;fono </td>
							<td><?php echo Form::text('proveedor.telefono'); ?></td>
					    </tr>
						<tr>
							<td>M&oacute;vil</td>
							<td><?php echo Form::text('proveedor.movil'); ?></td>
					    </tr>
						<tr>
							<td>Correo electr&oacute;nico  </td>
							<td><?php echo Form::text('proveedor.email'); ?></td>
					    </tr>
												<tr>
							<td>Direcci&oacute;n web </td>
							<td><?php echo Form::text('proveedor.web'); ?></td>
					    </tr>
					</table>
			  </div>
				<div id="botonBusqueda">
					<?php echo Form::hidden('proveedor.borrado',null,0); ?>
					<?php echo Form::submitImage('botonnuevoproveedor.jpg') ?>
					<button type="reset"><img src="<?php echo PUBLIC_PATH . 'img/botonlimpiar.jpg'?>" /></button>
					<img src="../img/botonaceptar.jpg" width="85" height="22" onClick="validar(formulario,true)" border="1" onMouseOver="style.cursor=cursor">
					<img src="../img/botonlimpiar.jpg" width="69" height="22" onClick="limpiar()" border="1" onMouseOver="style.cursor=cursor">
					<img src="../img/botoncancelar.jpg" width="85" height="22" onClick="cancelar()" border="1" onMouseOver="style.cursor=cursor">
					<input id="accion" name="accion" value="alta" type="hidden">
					<input id="id" name="id" value="" type="hidden">
			  </div>
			  <?php echo Form::close() ?>
		  </div>
		  </div>
		</div>
