<div id="pagina">
	<div id="zonaContenido">
	<div align="center">
		<div id="tituloForm" class="header">Buscar PROVEEDOR </div>
		<div id="frmBusqueda">
		<?php echo Form::open(); ?>
			<table class="fuente8" width="98%" cellspacing=0 cellpadding=3 border=0>					
				<tr>
					<td width="16%">Codigo de proveedor </td>
					<td width="68%"><?php echo Form::text('proveedores.id') ?>  <img src="../img/ver.png" width="16" height="16" onClick="abreVentana()" title="Buscar proveedor" onMouseOver="style.cursor=cursor"> <img src="../img/cliente.png" width="16" height="16" onClick="validarproveedor()" title="Validar proveedor" onMouseOver="style.cursor=cursor"></td>
					<td width="5%">&nbsp;</td>
					<td width="5%">&nbsp;</td>
					<td width="6%" align="right"></td>
				</tr>
				<tr>
					<td>Nombre</td>
					<td><?php echo Form::text('proveedores.nombre') ?></td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
				  <td>NIF / CIF</td>
				  <td><?php echo Form::text('proveedores.nif') ?></td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
			  </tr>
				<tr>
					<td>Provincia</td>
					<td><?php echo Form::dbSelect('proveedores.provincias_id'); ?></td>
				</tr>
			  <tr>
				  <td>Localidad</td>
				  <td><?php echo Form::text('proveedores.localidad') ?></td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
			  </tr>
				<tr>
				  <td>Tel&eacute;fono</td>
				  <td><?php echo Form::text('proveedores.telefono') ?></td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
			  </tr>
			</table>
	  </div>
		<div id="botonBusqueda"><?php echo Form::submit('Buscar') ?>
			<?php echo Html::linkAction("nuevo", Html::img('botonlimpiar.jpg')); ?>
			<?php echo Html::linkAction("nuevo", Html::img('botonnuevoproveedor.jpg')); ?>
			<?php echo Html::linkAction("imprimir", Html::img('botonimprimir.jpg')); ?>
		</div>
	  <?php echo Form::close() ?>
	  <div id="lineaResultado">
	  <table class="fuente8" width="80%" cellspacing=0 cellpadding=3 border=0>
		<tr>
		<td width="50%" align="left">N de proveedores encontrados <input id="filas" type="text" class="cajaPequena" NAME="filas" maxlength="5" value="<?php echo count($listProveedores->items); ?>" readonly></td>
		<td width="50%" align="right"><?php if($listProveedores->prev) echo Html::linkAction("index/$listProveedores->prev/", '<< Anterior |'); ?>
    <?php if($listProveedores->next) echo Html::linkAction("index/$listProveedores->next/", 'Próximo >>'); ?></td>
	  </table>
		</div>
		<div id="cabeceraResultado" class="header">
			relacion de PROVEEDORES </div>
		<div id="frmResultado">
		<table class="fuente8" width="100%" cellspacing=0 cellpadding=3 border=0 ID="Table1">
				<tr class="cabeceraTabla">
					<td width="8%">ITEM</td>
					<td width="6%">CODIGO</td>
					<td width="38%">NOMBRE </td>
					<td width="13%">NIF/CIF</td>
					<td width="19%">TELEFONO</td>
					<td width="5%">&nbsp;</td>
					<td width="5%">&nbsp;</td>
					<td width="6%">&nbsp;</td>
				</tr>
				<?php $contador=0; ?>
				<?php foreach ($listProveedores->items as $item) : ?>
					<?php if ($contador % 2) { $fondolinea="itemParTabla"; } else { $fondolinea="itemImparTabla"; } ?>
					<tr class="<?php echo $fondolinea?>">
						<td class="aCentro" width="8%"><? echo $contador+1;?></td>
						<td width="6%"><div align="center"><?php echo $item->id ?></div></td>
						<td width="38%"><div align="left"><?php echo $item->nombre ?></div></td>
						<td class="aDerecha" width="13%"><div align="center"><?php echo $item->nif ?></div></td>
						<td class="aDerecha" width="19%"><div align="center"><?php echo $item->telefono ?></div></td>
						<td width="5%"><div align="center"><?php echo Html::linkAction("edit/$item->id/", Html::img('modificar.png')); ?></div></td>
						<td width="5%"><div align="center"><?php echo Html::linkAction("view/$item->id/", Html::img('ver.png')); ?></div></td>
						<td width="6%"><div align="center"><?php echo Html::linkAction("del/$item->id/", Html::img('eliminar.png')); ?></div></td>
					</tr>
					<?php $contador++; ?>
				<?php endforeach; ?>
		</table>
</div>
