<!DOCTYPE html>
<html lang="es">
<html>
    <head>
        <title>Codeka Facturacion Web</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <?php Tag::css('theme'); ?>
        <?php echo Html::includeCss(); ?>
        
        <?php echo Tag::js('JSCookMenu'); ?>
        <?php echo Tag::js('theme'); ?>
        
    </head>
    <body>
        <?php View::partial('/codeku/menu') ?>
        <?php View::content() ?>
    </body>
</html>
